import { PrismaClient, UserRole, ProductCondition } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Create admin user
  const hashedPassword = await bcrypt.hash('admin123', 10);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@carparts.com' },
    update: {},
    create: {
      email: 'admin@carparts.com',
      name: 'Admin User',
      password: hashedPassword,
      role: UserRole.ADMIN,
    },
  });

  // Create test user
  const userPassword = await bcrypt.hash('user123', 10);
  const user = await prisma.user.upsert({
    where: { email: 'user@test.com' },
    update: {},
    create: {
      email: 'user@test.com',
      name: 'Test User',
      password: userPassword,
      role: UserRole.USER,
    },
  });

  console.log('Users created:', { admin, user });

  // Create categories
  const categories = await Promise.all([
    prisma.category.upsert({
      where: { slug: 'engine-parts' },
      update: {},
      create: {
        name: 'Engine Parts',
        slug: 'engine-parts',
        description: 'All engine related parts',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'brake-system' },
      update: {},
      create: {
        name: 'Brake System',
        slug: 'brake-system',
        description: 'Brake pads, discs, and more',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'suspension' },
      update: {},
      create: {
        name: 'Suspension',
        slug: 'suspension',
        description: 'Shock absorbers, springs, etc.',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'electrical' },
      update: {},
      create: {
        name: 'Electrical',
        slug: 'electrical',
        description: 'Batteries, alternators, starters',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'filters' },
      update: {},
      create: {
        name: 'Filters',
        slug: 'filters',
        description: 'Oil, air, fuel filters',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'exhaust' },
      update: {},
      create: {
        name: 'Exhaust System',
        slug: 'exhaust',
        description: 'Mufflers, pipes, catalytic converters',
      },
    }),
  ]);

  console.log('Categories created:', categories.length);

  // Create brands
  const brands = await Promise.all([
    prisma.brand.upsert({
      where: { slug: 'bosch' },
      update: {},
      create: { name: 'Bosch', slug: 'bosch', description: 'German engineering excellence' },
    }),
    prisma.brand.upsert({
      where: { slug: 'brembo' },
      update: {},
      create: { name: 'Brembo', slug: 'brembo', description: 'Premium brake systems' },
    }),
    prisma.brand.upsert({
      where: { slug: 'denso' },
      update: {},
      create: { name: 'Denso', slug: 'denso', description: 'Japanese OEM quality' },
    }),
    prisma.brand.upsert({
      where: { slug: 'mann-filter' },
      update: {},
      create: { name: 'Mann Filter', slug: 'mann-filter', description: 'Premium filtration' },
    }),
    prisma.brand.upsert({
      where: { slug: 'sachs' },
      update: {},
      create: { name: 'Sachs', slug: 'sachs', description: 'Suspension experts' },
    }),
    prisma.brand.upsert({
      where: { slug: 'valeo' },
      update: {},
      create: { name: 'Valeo', slug: 'valeo', description: 'Automotive innovation' },
    }),
  ]);

  console.log('Brands created:', brands.length);

  // Create products
  const products = [
    {
      title: 'Bosch Oil Filter',
      slug: 'bosch-oil-filter-0451103336',
      description: 'High-quality oil filter suitable for most European cars. Ensures optimal engine protection.',
      price: 25.99,
      discount: 0,
      sku: 'BOF-0451103336',
      categoryId: categories[4].id,
      brandId: brands[0].id,
      condition: ProductCondition.NEW,
      stock: 50,
      carMake: 'Mercedes-Benz',
      carModel: 'C-Class',
      yearFrom: 2014,
      yearTo: 2021,
      engine: '2.0L Diesel',
      attributes: JSON.stringify({ OEM: 'Yes', Material: 'Paper', WarrantyMonths: 12 }),
    },
    {
      title: 'Brembo Front Brake Pads',
      slug: 'brembo-brake-pads-p85020',
      description: 'Premium ceramic brake pads for superior stopping power and reduced dust.',
      price: 89.99,
      discount: 10,
      sku: 'BRE-P85020',
      categoryId: categories[1].id,
      brandId: brands[1].id,
      condition: ProductCondition.NEW,
      stock: 30,
      carMake: 'BMW',
      carModel: '3 Series',
      yearFrom: 2012,
      yearTo: 2019,
      attributes: JSON.stringify({ Type: 'Ceramic', Position: 'Front', WarrantyMonths: 24 }),
    },
    {
      title: 'Denso Spark Plugs Set',
      slug: 'denso-spark-plugs-k20hr-u11',
      description: 'Set of 4 spark plugs with iridium tips for better fuel efficiency and performance.',
      price: 45.50,
      discount: 5,
      sku: 'DEN-K20HRU11',
      categoryId: categories[0].id,
      brandId: brands[2].id,
      condition: ProductCondition.NEW,
      stock: 100,
      carMake: 'Toyota',
      carModel: 'Camry',
      yearFrom: 2015,
      yearTo: 2023,
      engine: '2.5L Petrol',
      attributes: JSON.stringify({ Material: 'Iridium', Quantity: 4, Gap: '1.1mm' }),
    },
    {
      title: 'Mann Air Filter',
      slug: 'mann-air-filter-c3698-3',
      description: 'High-performance air filter for improved engine breathing and fuel economy.',
      price: 18.99,
      discount: 0,
      sku: 'MAN-C36983',
      categoryId: categories[4].id,
      brandId: brands[3].id,
      condition: ProductCondition.NEW,
      stock: 75,
      carMake: 'Volkswagen',
      carModel: 'Golf',
      yearFrom: 2013,
      yearTo: 2020,
      attributes: JSON.stringify({ FilterType: 'Paper', Dimensions: '250x200x60mm' }),
    },
    {
      title: 'Sachs Shock Absorber',
      slug: 'sachs-shock-absorber-310650',
      description: 'Heavy-duty shock absorber for smooth and comfortable ride.',
      price: 125.00,
      discount: 15,
      sku: 'SAC-310650',
      categoryId: categories[2].id,
      brandId: brands[4].id,
      condition: ProductCondition.NEW,
      stock: 20,
      carMake: 'Audi',
      carModel: 'A4',
      yearFrom: 2016,
      yearTo: 2022,
      attributes: JSON.stringify({ Position: 'Front Right', Type: 'Gas', WarrantyMonths: 36 }),
    },
    {
      title: 'Valeo Alternator',
      slug: 'valeo-alternator-2606526',
      description: '120A alternator with premium copper windings for reliable charging.',
      price: 210.00,
      discount: 20,
      sku: 'VAL-2606526',
      categoryId: categories[3].id,
      brandId: brands[5].id,
      condition: ProductCondition.NEW,
      stock: 15,
      carMake: 'Renault',
      carModel: 'Megane',
      yearFrom: 2014,
      yearTo: 2020,
      attributes: JSON.stringify({ Output: '120A', Voltage: '12V', Type: 'Remanufactured' }),
    },
    {
      title: 'Bosch Battery 70Ah',
      slug: 'bosch-battery-s4007',
      description: 'Reliable 70Ah battery with 5-year warranty. Cold start 760A.',
      price: 155.00,
      discount: 0,
      sku: 'BOB-S4007',
      categoryId: categories[3].id,
      brandId: brands[0].id,
      condition: ProductCondition.NEW,
      stock: 40,
      attributes: JSON.stringify({ Capacity: '70Ah', CCA: '760A', WarrantyMonths: 60 }),
      isFeatured: true,
    },
    {
      title: 'Mann Cabin Air Filter',
      slug: 'mann-cabin-filter-cu2842',
      description: 'Activated carbon cabin filter for clean air inside the vehicle.',
      price: 22.50,
      discount: 0,
      sku: 'MAN-CU2842',
      categoryId: categories[4].id,
      brandId: brands[3].id,
      condition: ProductCondition.NEW,
      stock: 60,
      carMake: 'Honda',
      carModel: 'Civic',
      yearFrom: 2016,
      yearTo: 2023,
      attributes: JSON.stringify({ Type: 'Activated Carbon', Filtration: '99%' }),
    },
    {
      title: 'Brembo Brake Disc Set',
      slug: 'brembo-brake-disc-09a92511',
      description: 'Pair of ventilated brake discs for enhanced cooling and braking.',
      price: 145.00,
      discount: 12,
      sku: 'BRE-09A92511',
      categoryId: categories[1].id,
      brandId: brands[1].id,
      condition: ProductCondition.NEW,
      stock: 25,
      carMake: 'Ford',
      carModel: 'Focus',
      yearFrom: 2015,
      yearTo: 2022,
      attributes: JSON.stringify({ Diameter: '300mm', Thickness: '28mm', Ventilated: 'Yes' }),
      isFeatured: true,
    },
    {
      title: 'Denso Fuel Pump',
      slug: 'denso-fuel-pump-950-0201',
      description: 'Electric fuel pump with high flow rate for optimal fuel delivery.',
      price: 95.00,
      discount: 0,
      sku: 'DEN-9500201',
      categoryId: categories[0].id,
      brandId: brands[2].id,
      condition: ProductCondition.NEW,
      stock: 35,
      carMake: 'Mazda',
      carModel: 'CX-5',
      yearFrom: 2017,
      yearTo: 2023,
      attributes: JSON.stringify({ FlowRate: '150L/h', Pressure: '3.5bar' }),
    },
    {
      title: 'Sachs Coil Spring',
      slug: 'sachs-coil-spring-996719',
      description: 'Front coil spring for improved handling and comfort.',
      price: 65.00,
      discount: 0,
      sku: 'SAC-996719',
      categoryId: categories[2].id,
      brandId: brands[4].id,
      condition: ProductCondition.NEW,
      stock: 45,
      carMake: 'Opel',
      carModel: 'Astra',
      yearFrom: 2015,
      yearTo: 2021,
      attributes: JSON.stringify({ Position: 'Front', WireThickness: '13.5mm' }),
    },
    {
      title: 'Valeo Wiper Blades',
      slug: 'valeo-wiper-blades-574338',
      description: 'Set of 2 flat wiper blades with natural rubber for streak-free wiping.',
      price: 32.00,
      discount: 0,
      sku: 'VAL-574338',
      categoryId: categories[3].id,
      brandId: brands[5].id,
      condition: ProductCondition.NEW,
      stock: 80,
      attributes: JSON.stringify({ Length: '600mm/450mm', Type: 'Flat', Quantity: 2 }),
    },
    {
      title: 'Bosch Fuel Filter',
      slug: 'bosch-fuel-filter-0450906467',
      description: 'Diesel fuel filter with water separator for engine protection.',
      price: 28.00,
      discount: 0,
      sku: 'BOF-0450906467',
      categoryId: categories[4].id,
      brandId: brands[0].id,
      condition: ProductCondition.NEW,
      stock: 55,
      carMake: 'Peugeot',
      carModel: '308',
      yearFrom: 2013,
      yearTo: 2020,
      engine: '1.6L Diesel',
      attributes: JSON.stringify({ FuelType: 'Diesel', WaterSeparator: 'Yes' }),
    },
    {
      title: 'Brembo Brake Caliper',
      slug: 'brembo-brake-caliper-f85148',
      description: 'Remanufactured brake caliper with 2-year warranty.',
      price: 180.00,
      discount: 25,
      sku: 'BRE-F85148',
      categoryId: categories[1].id,
      brandId: brands[1].id,
      condition: ProductCondition.USED,
      stock: 10,
      carMake: 'Audi',
      carModel: 'A6',
      yearFrom: 2011,
      yearTo: 2018,
      attributes: JSON.stringify({ Position: 'Front Left', Pistons: 2, Remanufactured: 'Yes' }),
    },
    {
      title: 'Denso Lambda Sensor',
      slug: 'denso-lambda-sensor-dox-0258',
      description: 'Oxygen sensor for precise fuel mixture control.',
      price: 75.00,
      discount: 0,
      sku: 'DEN-DOX0258',
      categoryId: categories[0].id,
      brandId: brands[2].id,
      condition: ProductCondition.NEW,
      stock: 40,
      carMake: 'Nissan',
      carModel: 'Qashqai',
      yearFrom: 2014,
      yearTo: 2021,
      attributes: JSON.stringify({ Wires: 4, Position: 'Pre-Cat' }),
    },
    {
      title: 'Mann Oil Filter Premium',
      slug: 'mann-oil-filter-hu925-4x',
      description: 'Premium oil filter with metal-free design for environmental protection.',
      price: 32.00,
      discount: 0,
      sku: 'MAN-HU9254X',
      categoryId: categories[4].id,
      brandId: brands[3].id,
      condition: ProductCondition.NEW,
      stock: 70,
      carMake: 'BMW',
      carModel: 'X5',
      yearFrom: 2014,
      yearTo: 2022,
      engine: '3.0L Diesel',
      attributes: JSON.stringify({ Type: 'Metal-free', OEM: 'Yes', WarrantyMonths: 24 }),
      isFeatured: true,
    },
    {
      title: 'Sachs Clutch Kit',
      slug: 'sachs-clutch-kit-3000951501',
      description: 'Complete clutch kit with plate, disc, and release bearing.',
      price: 285.00,
      discount: 30,
      sku: 'SAC-3000951501',
      categoryId: categories[0].id,
      brandId: brands[4].id,
      condition: ProductCondition.NEW,
      stock: 12,
      carMake: 'Volkswagen',
      carModel: 'Passat',
      yearFrom: 2011,
      yearTo: 2019,
      gearbox: 'Manual',
      attributes: JSON.stringify({ Diameter: '240mm', Components: 3, WarrantyMonths: 24 }),
    },
    {
      title: 'Valeo Starter Motor',
      slug: 'valeo-starter-motor-458178',
      description: 'Remanufactured starter motor with 1-year warranty.',
      price: 165.00,
      discount: 15,
      sku: 'VAL-458178',
      categoryId: categories[3].id,
      brandId: brands[5].id,
      condition: ProductCondition.USED,
      stock: 18,
      carMake: 'Citroen',
      carModel: 'C4',
      yearFrom: 2013,
      yearTo: 2020,
      attributes: JSON.stringify({ Power: '1.4kW', Teeth: 10, Remanufactured: 'Yes' }),
    },
    {
      title: 'Bosch Ignition Coil',
      slug: 'bosch-ignition-coil-0221504024',
      description: 'High-performance ignition coil for reliable engine starting.',
      price: 68.00,
      discount: 0,
      sku: 'BOI-0221504024',
      categoryId: categories[0].id,
      brandId: brands[0].id,
      condition: ProductCondition.NEW,
      stock: 42,
      carMake: 'Skoda',
      carModel: 'Octavia',
      yearFrom: 2013,
      yearTo: 2020,
      engine: '1.8L Petrol',
      attributes: JSON.stringify({ Type: 'Pencil', Voltage: '12V' }),
    },
    {
      title: 'Brembo Brake Fluid DOT 4',
      slug: 'brembo-brake-fluid-dot4-500ml',
      description: '500ml bottle of high-performance DOT 4 brake fluid.',
      price: 12.50,
      discount: 0,
      sku: 'BRE-BF4500',
      categoryId: categories[1].id,
      brandId: brands[1].id,
      condition: ProductCondition.NEW,
      stock: 100,
      attributes: JSON.stringify({ Volume: '500ml', Type: 'DOT 4', BoilingPoint: '260°C' }),
    },
    {
      title: 'Denso Radiator',
      slug: 'denso-radiator-drm32066',
      description: 'Aluminum radiator with plastic tanks for efficient cooling.',
      price: 195.00,
      discount: 10,
      sku: 'DEN-DRM32066',
      categoryId: categories[0].id,
      brandId: brands[2].id,
      condition: ProductCondition.NEW,
      stock: 15,
      carMake: 'Hyundai',
      carModel: 'i30',
      yearFrom: 2012,
      yearTo: 2017,
      attributes: JSON.stringify({ Material: 'Aluminum', Rows: 2, WithAC: 'Yes' }),
    },
    {
      title: 'Mann Fuel Filter Diesel',
      slug: 'mann-fuel-filter-wk820-18',
      description: 'High-efficiency diesel fuel filter with integrated water separator.',
      price: 35.00,
      discount: 0,
      sku: 'MAN-WK82018',
      categoryId: categories[4].id,
      brandId: brands[3].id,
      condition: ProductCondition.NEW,
      stock: 50,
      carMake: 'Mercedes-Benz',
      carModel: 'Sprinter',
      yearFrom: 2013,
      yearTo: 2023,
      engine: '2.1L Diesel',
      attributes: JSON.stringify({ WaterSeparator: 'Yes', Efficiency: '98%' }),
    },
    {
      title: 'Sachs Suspension Strut',
      slug: 'sachs-suspension-strut-311862',
      description: 'Complete strut assembly with spring and mount.',
      price: 245.00,
      discount: 20,
      sku: 'SAC-311862',
      categoryId: categories[2].id,
      brandId: brands[4].id,
      condition: ProductCondition.NEW,
      stock: 14,
      carMake: 'Toyota',
      carModel: 'RAV4',
      yearFrom: 2013,
      yearTo: 2018,
      attributes: JSON.stringify({ Position: 'Front Right', Type: 'Gas', Complete: 'Yes' }),
    },
    {
      title: 'Valeo Headlight Bulb H7',
      slug: 'valeo-headlight-h7-032009',
      description: 'Standard halogen H7 bulb with 30% more light.',
      price: 8.50,
      discount: 0,
      sku: 'VAL-032009',
      categoryId: categories[3].id,
      brandId: brands[5].id,
      condition: ProductCondition.NEW,
      stock: 120,
      attributes: JSON.stringify({ Type: 'H7', Wattage: '55W', LightIncrease: '30%' }),
    },
    {
      title: 'Bosch Timing Belt Kit',
      slug: 'bosch-timing-belt-kit-1987946309',
      description: 'Complete timing belt kit with tensioner and water pump.',
      price: 175.00,
      discount: 15,
      sku: 'BOT-1987946309',
      categoryId: categories[0].id,
      brandId: brands[0].id,
      condition: ProductCondition.NEW,
      stock: 22,
      carMake: 'Ford',
      carModel: 'Mondeo',
      yearFrom: 2010,
      yearTo: 2018,
      engine: '2.0L Diesel',
      attributes: JSON.stringify({ Components: 4, WaterPump: 'Yes', WarrantyMonths: 24 }),
      isFeatured: true,
    },
  ];

  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: {},
      create: product,
    });
  }

  console.log('Products created: 25');
  console.log('Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
